name: testmod
version: '1'
description: Test Mod
main: org.example.TestMod
api-version: '1.20' # other known affected api-version is 1.18
load: STARTUP
website: https://github.com/burdoto/reproduce-virtual-anvil-null-item
commands:
  openanvil:
    description: open test anvil inventory